In [1]:
#import libraries
import pandas as pd
import numpy as np

In [3]:
#load dataset
df=pd.read_excel(r"C:\Users\Hp\Downloads\ApexPlanet_DataAnalytics_Dataset.xlsx")
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,city,product,Age_Group,Revenue_Per_Unit
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,Bengaluru,Rice,Adult,2829.77
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,Bengaluru,Book,Senior,27906.16
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,Bengaluru,Book,Senior,37491.06
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,Kolkata,Mobile,Senior,28541.36
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,Bengaluru,Rice,Middle,14036.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD100997,2025-11-07,CUST6410,Customer_301,61.0,Male,Gaya,Laptop,Electronics,9,35405.54,318649.86,Gaya,Laptop,Senior,35405.54
996,ORD100998,2025-09-03,CUST7618,Customer_154,25.0,Male,Gaya,Shoes,Fashion,5,18454.65,92273.25,Gaya,Shoes,Young,18454.65
997,ORD100999,2025-09-30,CUST9544,Customer_140,62.0,Female,Hyderabad,Laptop,Electronics,9,12971.59,116744.31,Hyderabad,Laptop,Senior,12971.59
998,ORD101000,2025-02-21,CUST9501,Customer_241,NaN,Male,Delhi,Mobile,Electronics,9,2879.01,25911.09,Delhi,Mobile,NaN,2879.01
999,ORD101001,2025-04-23,CUST2714,Customer_98,58.0,Female,Gaya,Chair,Furniture,9,22493.87,202444.83,Gaya,Chair,Middle,22493.87

In [4]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,city,product,Age_Group,Revenue_Per_Unit
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,Bengaluru,Rice,Adult,2829.77
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,Bengaluru,Book,Senior,27906.16
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,Bengaluru,Book,Senior,37491.06
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,Kolkata,Mobile,Senior,28541.36
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,Bengaluru,Rice,Middle,14036.59

In [5]:
df.tail()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,city,product,Age_Group,Revenue_Per_Unit
995,ORD100997,2025-11-07,CUST6410,Customer_301,61.0,Male,Gaya,Laptop,Electronics,9,35405.54,318649.86,Gaya,Laptop,Senior,35405.54
996,ORD100998,2025-09-03,CUST7618,Customer_154,25.0,Male,Gaya,Shoes,Fashion,5,18454.65,92273.25,Gaya,Shoes,Young,18454.65
997,ORD100999,2025-09-30,CUST9544,Customer_140,62.0,Female,Hyderabad,Laptop,Electronics,9,12971.59,116744.31,Hyderabad,Laptop,Senior,12971.59
998,ORD101000,2025-02-21,CUST9501,Customer_241,NaN,Male,Delhi,Mobile,Electronics,9,2879.01,25911.09,Delhi,Mobile,NaN,2879.01
999,ORD101001,2025-04-23,CUST2714,Customer_98,58.0,Female,Gaya,Chair,Furniture,9,22493.87,202444.83,Gaya,Chair,Middle,22493.87

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1000 non-null   object
 1   Order_Date        1000 non-null   object
 2   Customer_ID       1000 non-null   object
 3   Customer_Name     1000 non-null   object
 4   Age               980 non-null    float64
 5   Gender            1000 non-null   object
 6   City              987 non-null    object
 7   Product           1000 non-null   object
 8   Category          1000 non-null   object
 9   Quantity          1000 non-null   int64
 10  Unit_Price        1000 non-null   float64
 11  Total_Sales       1000 non-null   float64
 12  city              987 non-null    object
 13  product           1000 non-null   object
 14  Age_Group         980 non-null    object
 15  Revenue_Per_Unit  1000 non-null   float64
dtypes: float64(4), int64(1), object(11)
memory usage: 125.1+ KB

In [8]:
df.describe()

              Age     Quantity    Unit_Price    Total_Sales  Revenue_Per_Unit
count  980.000000  1000.000000   1000.000000    1000.000000       1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650      25486.783410
std     13.822597     2.838632  14179.402361  114100.051546      14179.402361
min     18.000000     1.000000    145.780000     437.340000        145.780000
25%     30.000000     3.000000  13895.722500   47066.632500      13895.722500
50%     41.000000     5.000000  25398.740000  108594.025000      25398.740000
75%     54.000000     8.000000  37512.382500  203722.882500      37512.382500
max     65.000000    10.000000  49997.530000  493677.500000      49997.530000

In [9]:
df.shape

(1000, 16)

In [10]:
df.dtypes

Order_ID             object
Order_Date           object
Customer_ID          object
Customer_Name        object
Age                 float64
Gender               object
City                 object
Product              object
Category             object
Quantity              int64
Unit_Price          float64
Total_Sales         float64
city                 object
product              object
Age_Group            object
Revenue_Per_Unit    float64
dtype: object

In [11]:
#Data Quality Accessment
df.isnull().sum()

Order_ID             0
Order_Date           0
Customer_ID          0
Customer_Name        0
Age                 20
Gender               0
City                13
Product              0
Category             0
Quantity             0
Unit_Price           0
Total_Sales          0
city                13
product              0
Age_Group           20
Revenue_Per_Unit     0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.drop_duplicates()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,city,product,Age_Group,Revenue_Per_Unit,Order_Month
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,Bengaluru,Rice,Young Adult,2829.77,2
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,Bengaluru,Book,Senior,27906.16,10
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,Bengaluru,Book,Senior,37491.06,5
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,Kolkata,Mobile,Senior,28541.36,12
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,Bengaluru,Rice,Adult,14036.59,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD100997,2025-11-07,CUST6410,Customer_301,61.0,Male,Gaya,Laptop,Electronics,9,35405.54,318649.86,Gaya,Laptop,Senior,35405.54,11
996,ORD100998,2025-09-03,CUST7618,Customer_154,25.0,Male,Gaya,Shoes,Fashion,5,18454.65,92273.25,Gaya,Shoes,Young Adult,18454.65,9
997,ORD100999,2025-09-30,CUST9544,Customer_140,62.0,Female,Hyderabad,Laptop,Electronics,9,12971.59,116744.31,Hyderabad,Laptop,Senior,12971.59,9
998,ORD101000,2025-02-21,CUST9501,Customer_241,41.0,Male,Delhi,Mobile,Electronics,9,2879.01,25911.09,Delhi,Mobile,Adult,2879.01,2
999,ORD101001,2025-04-23,CUST2714,Customer_98,58.0,Female,Gaya,Chair,Furniture,9,22493.87,202444.83,Gaya,Chair,Senior,22493.87,4

In [22]:
df['Age']=df['Age'].fillna(df['Age'].median())
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,city,product,Age_Group,Revenue_Per_Unit
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,Bengaluru,Rice,Adult,2829.77
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,Bengaluru,Book,Senior,27906.16
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,Bengaluru,Book,Senior,37491.06
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,Kolkata,Mobile,Senior,28541.36
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,Bengaluru,Rice,Middle,14036.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD100997,2025-11-07,CUST6410,Customer_301,61.0,Male,Gaya,Laptop,Electronics,9,35405.54,318649.86,Gaya,Laptop,Senior,35405.54
996,ORD100998,2025-09-03,CUST7618,Customer_154,25.0,Male,Gaya,Shoes,Fashion,5,18454.65,92273.25,Gaya,Shoes,Young,18454.65
997,ORD100999,2025-09-30,CUST9544,Customer_140,62.0,Female,Hyderabad,Laptop,Electronics,9,12971.59,116744.31,Hyderabad,Laptop,Senior,12971.59
998,ORD101000,2025-02-21,CUST9501,Customer_241,41.0,Male,Delhi,Mobile,Electronics,9,2879.01,25911.09,Delhi,Mobile,NaN,2879.01
999,ORD101001,2025-04-23,CUST2714,Customer_98,58.0,Female,Gaya,Chair,Furniture,9,22493.87,202444.83,Gaya,Chair,Middle,22493.87

In [24]:
#standarization
df['city']=df['City'].str.title()
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,city,product,Age_Group,Revenue_Per_Unit
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,Bengaluru,Rice,Adult,2829.77
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,Bengaluru,Book,Senior,27906.16
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,Bengaluru,Book,Senior,37491.06
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,Kolkata,Mobile,Senior,28541.36
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,Bengaluru,Rice,Middle,14036.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD100997,2025-11-07,CUST6410,Customer_301,61.0,Male,Gaya,Laptop,Electronics,9,35405.54,318649.86,Gaya,Laptop,Senior,35405.54
996,ORD100998,2025-09-03,CUST7618,Customer_154,25.0,Male,Gaya,Shoes,Fashion,5,18454.65,92273.25,Gaya,Shoes,Young,18454.65
997,ORD100999,2025-09-30,CUST9544,Customer_140,62.0,Female,Hyderabad,Laptop,Electronics,9,12971.59,116744.31,Hyderabad,Laptop,Senior,12971.59
998,ORD101000,2025-02-21,CUST9501,Customer_241,41.0,Male,Delhi,Mobile,Electronics,9,2879.01,25911.09,Delhi,Mobile,NaN,2879.01
999,ORD101001,2025-04-23,CUST2714,Customer_98,58.0,Female,Gaya,Chair,Furniture,9,22493.87,202444.83,Gaya,Chair,Middle,22493.87

In [25]:
df['product']=df['Product'].str.title()
df

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,city,product,Age_Group,Revenue_Per_Unit
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,Bengaluru,Rice,Adult,2829.77
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,Bengaluru,Book,Senior,27906.16
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,Bengaluru,Book,Senior,37491.06
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,Kolkata,Mobile,Senior,28541.36
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,Bengaluru,Rice,Middle,14036.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD100997,2025-11-07,CUST6410,Customer_301,61.0,Male,Gaya,Laptop,Electronics,9,35405.54,318649.86,Gaya,Laptop,Senior,35405.54
996,ORD100998,2025-09-03,CUST7618,Customer_154,25.0,Male,Gaya,Shoes,Fashion,5,18454.65,92273.25,Gaya,Shoes,Young,18454.65
997,ORD100999,2025-09-30,CUST9544,Customer_140,62.0,Female,Hyderabad,Laptop,Electronics,9,12971.59,116744.31,Hyderabad,Laptop,Senior,12971.59
998,ORD101000,2025-02-21,CUST9501,Customer_241,41.0,Male,Delhi,Mobile,Electronics,9,2879.01,25911.09,Delhi,Mobile,NaN,2879.01
999,ORD101001,2025-04-23,CUST2714,Customer_98,58.0,Female,Gaya,Chair,Furniture,9,22493.87,202444.83,Gaya,Chair,Middle,22493.87

In [31]:
#DETECTING OULIERS AND REMOVING THEM 
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df["Age"] >= lower) & (df["Age"] <= upper)]

print("Outliers Removed Successfully")

Outliers Removed Successfully

In [37]:
#FEATURE EXTACTION 
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0,18,35,50,100],
    labels=["Teen","Young Adult","Adult","Senior"]
)

df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,city,product,Age_Group,Revenue_Per_Unit,Order_Month
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,Bengaluru,Rice,Young Adult,2829.77,2
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,Bengaluru,Book,Senior,27906.16,10
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,Bengaluru,Book,Senior,37491.06,5
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,Kolkata,Mobile,Senior,28541.36,12
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,Bengaluru,Rice,Adult,14036.59,11

In [35]:
df["Order_Month"] = pd.to_datetime(df["Order_Date"]).dt.month
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,city,product,Age_Group,Revenue_Per_Unit,Order_Month
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,Bengaluru,Rice,Young Adult,2829.77,2
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,Bengaluru,Book,Senior,27906.16,10
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,Bengaluru,Book,Senior,37491.06,5
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,Kolkata,Mobile,Senior,28541.36,12
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,Bengaluru,Rice,Adult,14036.59,11

In [36]:
df.to_csv("Cleaned_Dataset.csv", index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully